# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [28]:
# NumPy program to create a 2d array with 6 on the border and 0 inside
import numpy as np
zeroInsideMat = np.array([[6,6,6,6,6,6],[6,6,6,6,6,6],[6,6,6,6,6,6],[6,6,6,6,6,6],[6,6,6,6,6,6]])
zeroInsideMat[1:-1,1:-1]=0
zeroInsideMat

array([[6, 6, 6, 6, 6, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 0, 0, 0, 0, 6],
       [6, 6, 6, 6, 6, 6]])

Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [29]:
#NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern

checkerBoardMat = np.ones((8,8), dtype=int)

checkerBoardMat[::2,::2]=3
checkerBoardMat[1::2,::2]=9
checkerBoardMat[::2,1::2]=9
checkerBoardMat[1::2,1::2]=3
checkerBoardMat
#print('Print the Checker Board Matrix:\n',checkerBoardMat)

array([[3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3],
       [3, 9, 3, 9, 3, 9, 3, 9],
       [9, 3, 9, 3, 9, 3, 9, 3]])

Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [32]:
#NumPy program to create an empty and a full array.

print("Print the Empty Matrix: \n", np.empty((3,4)))
a = np.mat('6,6,6;6,6,6;6,6,6')
print("\nPrint the Full Array of Matrix: \n", a)

Print the Empty Matrix: 
 [[9.41027419e-312 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [6.23053953e-307 1.33664410e+160 6.20252931e-091 2.32002803e-056]
 [1.26091092e-076 9.16442913e-072 3.99910963e+252 1.46030983e-319]]

Print the Full Array of Matrix: 
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [33]:
#NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.

import numpy as np
fahrenheit_values = [0, 12, 45.21 ,34, 99.91]
fah = np.array(fahrenheit_values)
print("Values in Fahrenheit degrees-\n",fah)
print("Values in Centigrade degrees- \n",5*fah/9 - 5*32/9)


Values in Fahrenheit degrees-
 [ 0.   12.   45.21 34.   99.91]
Values in Centigrade degrees- 
 [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [34]:
#NumPy program to find the real and imaginary parts of an array of complex numbers?

import numpy as np

x = np.sqrt([1+0j])
y = np.sqrt([0+1j])
z =  np.array([x,y])

print('The Original Array : \n',z)
print('Real Part of the Array: \n',z.real)

print('Imaginary Part of the Array: \n',z.imag)

The Original Array : 
 [[1.        +0.j        ]
 [0.70710678+0.70710678j]]
Real Part of the Array: 
 [[1.        ]
 [0.70710678]]
Imaginary Part of the Array: 
 [[0.        ]
 [0.70710678]]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [35]:
#NumPy program to test whether each element of a 1-D array is also present in the second array

import numpy as np
arr1 = [0, 10, 20, 40, 60]
arr2 = [0, 40]

print("Array 1 :",arr1,"\nArray 2: ",arr2)

print('Compare each element of array1 and array2\n',np.in1d(arr1,arr2))

Array 1 : [0, 10, 20, 40, 60] 
Array 2:  [0, 40]
Compare each element of array1 and array2
 [ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [36]:
#NumPy program to find common values between two arrays

import numpy as np
arr1 = [0, 10, 20, 40, 60]
arr2 = [10, 30, 40]

print("Array 1 :",arr1,"\nArray 2: ",arr2)

print('Common values between two arrays\n',np.intersect1d(arr1,arr2))

Array 1 : [0, 10, 20, 40, 60] 
Array 2:  [10, 30, 40]
Common values between two arrays
 [10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [37]:
#NumPy program to get the unique elements of an array

import numpy as np
ori_arr1 = np.array([10,10,20,20,30,30])

print("Orininal array 1 -\n",ori_arr1)

print('Unique elements of the above array:\n',np.unique(ori_arr1))

ori_arr2 = np.array([[1,1],[2,3]])
print('\nOriginal array 2 -\n',ori_arr2)
print('Unique elements of the above array-\n',np.unique(ori_arr2))

Orininal array 1 -
 [10 10 20 20 30 30]
Unique elements of the above array:
 [10 20 30]

Original array 2 -
 [[1 1]
 [2 3]]
Unique elements of the above array-
 [1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [40]:
#NumPy program to find the set exclusive-or of two arrays.Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays

import numpy as np
arr1 = np.array([0,10,20,40,60,80])
print('Array 1-',arr1)
arr2 = np.array([10,30,40,50,70])
print('Array 2-',arr2)
print('\nUnique values that in only one (not both) of the input arrays-\n',np.setdiff1d(arr1,arr2))

Array 1- [ 0 10 20 40 60 80]
Array 2- [10 30 40 50 70]

Unique values that in only one (not both) of the input arrays-
 [ 0 20 60 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [41]:
#NumPy program to test if all elements in an array evaluate to True 

import numpy as np

print(np.all([[True,True],[False,True]])) # one element as False
print(np.all([[True,True],[True,True]]))
print(np.all([50, -70, 40, 100]))
print(np.all([0, 20, -50])) # 0 has one of the element

False
True
True
False


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [42]:
#NumPy program to test whether any array element along the given axis evaluates to True

import numpy as np

print(np.any([[True,True],[True,True]]))
print(np.any([[False,False],[False,False]]))

print(np.any([70, -40, 0, 30]))
print(np.any([20, 40, -80]))

True
False
True
True


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [43]:
#NumPy program to construct an array by repeating

import numpy as np

arr = [1,2,3,4]
print('Original Array-\n',arr)
print('Repeating 2 times-\n',np.tile(arr,2))
print('Repeating 3 times -\n',np.tile(arr,3))

Original Array-
 [1, 2, 3, 4]
Repeating 2 times-
 [1 2 3 4 1 2 3 4]
Repeating 3 times -
 [1 2 3 4 1 2 3 4 1 2 3 4]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [44]:
#NumPy program to find the indices of the maximum and minimum values with the given axis of an array

import numpy as np

arr = np.array([1,2,3,4,5,6])

print('Original Array :\n',arr)
print('Maximum Values :\n',np.argmax(arr))
print('Minimum Values :\n',np.argmin(arr))


Original Array :
 [1 2 3 4 5 6]
Maximum Values :
 5
Minimum Values :
 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [45]:
#NumPy program compare two arrays using numpy

import numpy as np

arr1 = np.array([1, 2])
arr2 = np.array([4, 5])

print("Array a: ",arr1)
print("Array b: ",arr2)
print("a > b")
print(np.greater(arr1,arr2))
print("a >= b")
print(np.greater_equal(arr1,arr2))
print("a < b")
print(np.less(arr1,arr2))
print("a <= b")
print(np.less_equal(arr1,arr2))

Array a:  [1 2]
Array b:  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [46]:
import numpy as np
arr = np.array([[4, 6],[2, 1]])
print("Original array: \n")
print(arr)
print("\nSort along the first axis- ")
x = np.sort(arr, axis=0)
print(x)
print("\nSort along the last axis- ")
y = np.sort(x, axis=1)
print(y)

Original array: 

[[4 6]
 [2 1]]

Sort along the first axis- 
[[2 1]
 [4 6]]

Sort along the last axis- 
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [47]:
#NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name).

import numpy as np

fnames =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
lnames = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')

ind = np.lexsort((fnames,lnames))
print(ind)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [49]:
#NumPy program to get the values and indices of the elements that are bigger than 10 in the given array

import numpy as np

arr = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ",arr)

print("Values bigger than 10 =", arr[arr>10])
print("Their indices are ", np.nonzero(arr > 10))


Original array:  [[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [50]:
#NumPy program to find the memory size of a NumPy array

import numpy as np

mem = np.zeros((4,4))
print("%d bytes" % (mem.size * mem.itemsize))

128 bytes
